### ISSUE TITLE
[Question] SPECs recommendation for hosting VM

### ISSUE THREAD

**Issue by terrynguyen255** [bmd1905/Vietnamese-Corrector#2]
Hi @bmd1905,

I'm sorry if it's inappropriate to create an issue for a question like this 🙏 

I'm experiencing a performance issue when hosting the model on my Mac Mini M1. It takes 5-7 mins to process a 500-char paragraph.
I'm not sure if hosting this into a cloud VM would be better, and what are the best SPECs options (in terms of performance & cost)? I expect it to process 500 chars in less than 2min (1min if the price is affordable).

I hope I'm not bothering you much.
Thank you in advance.

---
**My Mac Mini M1's SPECs:**
**RAM:** 16GB
**CPU:** Apple M1 chip
- 8-core CPU with 4 performance cores and 4 efficiency cores
- 8-core GPU
- 16-core Neural Engine

**Comment by bmd1905** [comment]
I'm sorry, I missed your question. I think you should do some pruning or quantizing your model first, and then the performance will significantly increase.

**Comment by terrynguyen255** [comment]
I will. Thank you so much @bmd1905
