### ISSUE TITLE
How can we control the problem that the model will generate the diffirent word?

### ISSUE THREAD

**Issue by anonymousz97** [bmd1905/Vietnamese-Corrector#4]
I know that this model is seq2seq so it is freely to generate next word but do you have any idea to handle the output will not generate diffirent word? For ex: 
'àV việc Rút vốn khỏi công ty của **mindich** là một phaafn trrrong mỗ lực đđđại tu quỹ hiếnnn tặng lên tới 37,5 tỉ USD của trường  - quỹ hiến tặng lớn nhất trong số các trường đại học , đónnng góp tới hơn 1/3 ngân sách hoạt nộđg của harvard trong năm tài chính gnầ nhất.',
 [{'generated_text': 'Và việc rút vốn khỏi công ty của **Harvard** là một phần trong nỗ lực để đại tu quỹ hiến tặng lên tới 37,5 tỉ USD của trường - quỹ hiến tặng lớn nhất trong số các trường đại học, đóng góp tới hơn 1/3 ngân sách hoạt động của Harvard trong năm tài chính gần nhất.'}],
 'Và việc rút vốn khỏi công ty của **Mindich** là một phần trong nỗ lực đại tu quỹ hiến tặng lên tới 37,5 tỉ USD của Trường  - quỹ hiến tặng lớn nhất trong số các trường đại học , đóng góp tới hơn 1/3 ngân sách hoạt động của Harvard trong năm tài chính gần nhất')

You can see in here that the model will change the word **mindich** into **Harvard** seems not good. Thanks

**Comment by bmd1905** [comment]
The dataset isn't large enough to convert all cases. I trained [a new version](https://huggingface.co/bmd1905/vietnamese-correction-v2) of this model a few days ago, and this is the result:

> Và việc rút vốn khỏi công ty của Mindich là một phần trong nỗ lực để đại tu quỹ hiến tặng lên tới 37,5 tỉ USD của trường - quỹ hiến tặng lớn nhất trong số các trường đại học , đóng góp tới hơn 1/3 ngân sách hoạt động của harvard trong năm tài chính gần nhất.

We still have some issues with this model. Some rare words need to be properly considered, and the need for understanding punctuation, such as the ',' character, persists. Additionally, the dataset is quite old, having been created seven years ago.

If you wish to fine-tune this model, consider using the [new notebook version](https://github.com/bmd1905/vietnamese-correction/blob/main/train_v2.ipynb), which is much easier to understand.

I will crawl new data and expand the dataset to address these issues. I'll see you in the next version.

**Comment by anonymousz97** [comment]
Thanks for your fast response, i will try to finetune the new version. Can you produce about the GPU using in this? We can have a chat to solve this problem. Thanks

**Comment by anonymousz97** [comment]
I can share my dataset too

**Comment by bmd1905** [comment]
I used a 24GB GPU, but a 12GB or Free version of Colab is sufficient for the model. You can inbox me through this mail: henry.bmduc@gmail.com
