### ISSUE TITLE
Customization from the original dataset

### ISSUE THREAD

**Issue by hoangngx** [bmd1905/Vietnamese-Corrector#5]
Hi anh Duc, I would like to know how you customized / transformed the original dataset (VNTC) from the correct sentences to the error ones.

Glad if you could share your methods. Thanks in advance!

**Comment by bmd1905** [comment]
Hi Hoang,

The code I used to generate the dataset can be found [here](https://github.com/bmd1905/vietnamese-correction/blob/main/custom_generate_dataset.py). Please don't hesitate to reach out if you have any questions. It would be best to refine this code using LLMs to create a more quality dataset.
